"""create_premio_solicitacao

Revision ID: 44232dc0fec2
Revises: fcf58f32ec47
Create Date: 2026-06-03 16:10:54.588033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44232dc0fec2'
down_revision = 'fcf58f32ec47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premio_solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tipo_premio', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indicador_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_indicado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_indicacao', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['indicador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_indicacao')
        batch_op.drop_column('is_indicado')
        batch_op.drop_column('indicador_id')

    op.drop_table('premio_solicitacao')
    # ### end Alembic commands ###
