"""adiciona campo public_id na tabela versao_robo

Revision ID: 5e1bbd8d5e9e
Revises: 9d2a503adaab
Create Date: 2026-06-10 13:01:51.309193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1bbd8d5e9e'
down_revision = '9d2a503adaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
