"""add_unique_user_ciclo_licenca

Revision ID: fcf58f32ec47
Revises: 151025e9410d
Create Date: 2026-06-02 18:54:30.682145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf58f32ec47'
down_revision = '151025e9410d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca_cliente', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_ciclo_uc', ['user_id', 'ciclo_inicio'])

    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('licenca_cliente', schema=None) as batch_op:
        batch_op.drop_constraint('_user_ciclo_uc', type_='unique')

    # ### end Alembic commands ###
