"""adiciona conta_mt5_id em parcela_compra e unique constraint em conta_mt5_cliente

Revision ID: 084437191764
Revises: 8eedd6505327
Create Date: 2026-06-16 11:17:11.575122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084437191764'
down_revision = '8eedd6505327'
branch_labels = None
depends_on = None

def upgrade():
    # 1. Adicionar coluna conta_mt5_id (nullable)
    with op.batch_alter_table('parcela_compra') as batch_op:
        batch_op.add_column(sa.Column('conta_mt5_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_parcela_conta', 'conta_mt5_cliente', ['conta_mt5_id'], ['id'])

    # 2. Migrar dados: associar parcelas à primeira conta ativa do cliente
    op.execute("""
        UPDATE parcela_compra p
        SET conta_mt5_id = (
            SELECT id FROM conta_mt5_cliente c
            WHERE c.user_id = p.user_id AND c.ativo = true
            ORDER BY c.id LIMIT 1
        )
        WHERE p.conta_mt5_id IS NULL
    """)

    # 3. Adicionar a constraint única em conta_mt5_cliente
    with op.batch_alter_table('conta_mt5_cliente') as batch_op:
        batch_op.create_unique_constraint('_user_conta_uc', ['user_id', 'numero_conta'])

    # 4. Tornar a coluna NOT NULL
    with op.batch_alter_table('parcela_compra') as batch_op:
        batch_op.alter_column('conta_mt5_id', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcela_compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conta_mt5_id')

    with op.batch_alter_table('conta_mt5_cliente', schema=None) as batch_op:
        batch_op.drop_constraint('_user_conta_uc', type_='unique')

    # ### end Alembic commands ###
