"""empty message

Revision ID: 09c2aa102c17
Revises: ec2dad855324
Create Date: 2026-05-11 10:48:26.411171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c2aa102c17'
down_revision = 'ec2dad855324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('autentique_id', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('autentique_document_id', sa.String(length=100), nullable=False),
    sa.Column('link_assinatura', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['documento_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_cliente')
    op.drop_table('documento_template')
    # ### end Alembic commands ###
