"""adiciona coluna is_isento na tabela user

Revision ID: 115bb3f731b1
Revises: 2a555a9dab57
Create Date: 2026-05-07 16:33:23.618220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115bb3f731b1'
down_revision = '2a555a9dab57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.create_unique_constraint('_fatura_dia_corretora_uc', ['fatura_id', 'data_pregao', 'nome_corretora'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_isento', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_isento')

    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.drop_constraint('_fatura_dia_corretora_uc', type_='unique')

    # ### end Alembic commands ###
