"""remove unique constraint from licenca_cliente

Revision ID: 151025e9410d
Revises: 83f78b70bcd6
Create Date: 2026-05-31 18:58:38.351180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151025e9410d'
down_revision = '83f78b70bcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_user_ciclo_uc'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('licenca_bloqueada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('licenca_bloqueada')

    with op.batch_alter_table('licenca_cliente', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('_user_ciclo_uc'), ['user_id', 'ciclo_inicio'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
