"""adiciona coluna de forcar troca de senha

Revision ID: 21cfe93f90c6
Revises: ad0f24a1e6e7
Create Date: 2026-05-05 10:15:13.691736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cfe93f90c6'
down_revision = 'ad0f24a1e6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precisa_trocar_senha', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('precisa_trocar_senha')

    # ### end Alembic commands ###
