"""adiciona_modelo_negocio_e_parcelas

Revision ID: 22debf812494
Revises: c9b06bd2cb37
Create Date: 2026-05-18 09:37:32.617018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22debf812494'
down_revision = 'c9b06bd2cb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcela_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('txid_pix', sa.String(length=100), nullable=True),
    sa.Column('payload_pix', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txid_pix', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payload_pix', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo_negocio', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modelo_negocio')

    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_column('payload_pix')
        batch_op.drop_column('txid_pix')

    op.drop_table('parcela_compra')
    # ### end Alembic commands ###
