"""Adiciona validacao CPF, ip_address no LogAuditoria e unique constraint em licenca_cliente

Revision ID: 315b1d5db804
Revises: 5e1bbd8d5e9e
Create Date: 2026-06-10 17:05:18.521140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b1d5db804'
down_revision = '5e1bbd8d5e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_controle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('download_controle_versao_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'versao_robo', ['versao_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_controle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('download_controle_versao_id_fkey'), 'versao_robo', ['versao_id'], ['id'])

    # ### end Alembic commands ###
