"""adiciona campo extensao em versao_robo

Revision ID: 4cc1780196bb
Revises: e0188ec6d94e
Create Date: 2026-05-27 00:59:37.347488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc1780196bb'
down_revision = 'e0188ec6d94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extensao', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.drop_column('extensao')

    # ### end Alembic commands ###
