"""add_produto_vitalicio_id_to_user

Revision ID: 58e8601c7896
Revises: 23c3bed51d66
Create Date: 2026-06-12 16:39:48.813078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e8601c7896'
down_revision = '23c3bed51d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_controle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_user_versao_ciclo_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_versao_uc', ['user_id', 'versao_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_vitalicio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'produto_robo', ['produto_vitalicio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_vitalicio_id')

    with op.batch_alter_table('download_controle', schema=None) as batch_op:
        batch_op.drop_constraint('_user_versao_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_versao_ciclo_uc'), ['user_id', 'versao_id', 'ciclo_inicio'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
