"""adiciona produto_robo, produto_id em versao_robo, ciclo_inicio em download_controle

Revision ID: 5a270dca24b2
Revises: 315b1d5db804
Create Date: 2026-06-11 10:25:13.875560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a270dca24b2'
down_revision = '315b1d5db804'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Cria a tabela produto_robo
    op.create_table('produto_robo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(length=50), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('ordem', sa.Integer(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )

    # 2. Insere um produto padrão (para associar às versões existentes)
    op.execute(
        "INSERT INTO produto_robo (slug, nome, descricao, ordem, ativo) VALUES "
        "('robo_padrao', 'Robô Padrão', 'Produto criado automaticamente para migração', 1, true)"
    )

    # 3. Adiciona a coluna produto_id como NULLABLE inicialmente
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_versao_robo_produto_id', 'produto_robo', ['produto_id'], ['id'])

    # 4. Atualiza os registros existentes para apontar para o produto padrão (id=1)
    op.execute("UPDATE versao_robo SET produto_id = 1 WHERE produto_id IS NULL")

    # 5. Agora torna a coluna NOT NULL
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.alter_column('produto_id', existing_type=sa.Integer(), nullable=False)

    # 6. Adiciona a coluna ciclo_inicio em download_controle (se ainda não tiver)
    with op.batch_alter_table('download_controle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo_inicio', sa.Date(), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versao_robo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')

    with op.batch_alter_table('download_controle', schema=None) as batch_op:
        batch_op.drop_column('ciclo_inicio')

    op.drop_table('produto_robo')
    # ### end Alembic commands ###
