"""multi_corretoras

Revision ID: 758cb15df1f4
Revises: cae51ed938c0
Create Date: 2026-05-06 21:08:38.222748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758cb15df1f4'
down_revision = 'cae51ed938c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alocacao_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_corretora', sa.String(length=50), nullable=False),
    sa.Column('capital_alocado', sa.Float(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_corretora', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.drop_column('nome_corretora')

    op.drop_table('alocacao_corretora')
    # ### end Alembic commands ###
