"""multi_corretoras

Revision ID: 758cb15df1f4
Revises: cae51ed938c0
Create Date: 2026-05-06 21:08:38.222748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758cb15df1f4'
down_revision = 'cae51ed938c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # BYPASS: Ignorando a criação pois a tabela 'alocacao_corretora' e a 
    # coluna 'nome_corretora' já foram forçadas via rota secreta no Neon DB.
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # BYPASS: Ignorando a exclusão
    pass

    # ### end Alembic commands ###


