"""adiciona campo robot_acesso_bloqueado na tabela user

Revision ID: 7a96c3e634b5
Revises: 44232dc0fec2
Create Date: 2026-06-07 19:26:08.749941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a96c3e634b5'
down_revision = '44232dc0fec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('robot_acesso_bloqueado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('robot_acesso_bloqueado')

    # ### end Alembic commands ###
