"""adiciona constraint unica global para numero_conta

Revision ID: 7aa56eb8f96c
Revises: f3e5e4a5d221
Create Date: 2026-06-17 10:54:51.023961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa56eb8f96c'
down_revision = 'f3e5e4a5d221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_mt5_cliente', schema=None) as batch_op:
        batch_op.alter_column('licenca_comprada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.create_unique_constraint('_global_numero_conta_uc', ['numero_conta'])

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notificacao_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('parcela_compra', schema=None) as batch_op:
        batch_op.alter_column('conta_mt5_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcela_compra', schema=None) as batch_op:
        batch_op.alter_column('conta_mt5_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notificacao_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('conta_mt5_cliente', schema=None) as batch_op:
        batch_op.drop_constraint('_global_numero_conta_uc', type_='unique')
        batch_op.alter_column('licenca_comprada',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
