"""adiciona conta_mt5 em user e campos em licenca_cliente

Revision ID: 83f78b70bcd6
Revises: 4cc1780196bb
Create Date: 2026-05-30 20:48:50.139578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f78b70bcd6'
down_revision = '4cc1780196bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('data_expiracao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('conta_mt5', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_mt5', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('conta_mt5')

    with op.batch_alter_table('licenca_cliente', schema=None) as batch_op:
        batch_op.drop_column('conta_mt5')
        batch_op.drop_column('status')
        batch_op.drop_column('data_expiracao')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
