"""adiciona campos relatorio_html_url, motivo_isencao e operacao_detectada na tabela fatura_diaria

Revision ID: 9d2a503adaab
Revises: 7a96c3e634b5
Create Date: 2026-06-08 10:09:19.496244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2a503adaab'
down_revision = '7a96c3e634b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio_html_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('motivo_isencao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('operacao_detectada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.drop_column('operacao_detectada')
        batch_op.drop_column('motivo_isencao')
        batch_op.drop_column('relatorio_html_url')

    # ### end Alembic commands ###
