"""adicionando colunas de liquido pregao e irrf 19

Revision ID: ad0f24a1e6e7
Revises: 
Create Date: 2026-05-05 09:07:42.420072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0f24a1e6e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquido_pregao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('irrf_19', sa.Float(), nullable=True))

    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquido_pregao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('irrf_19', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.drop_column('irrf_19')
        batch_op.drop_column('liquido_pregao')

    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_column('irrf_19')
        batch_op.drop_column('liquido_pregao')

    # ### end Alembic commands ###
