"""adiciona robos demo e controle de download

Revision ID: b11c3d63350c
Revises: 7aa56eb8f96c
Create Date: 2026-06-23 20:52:31.172568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11c3d63350c'
down_revision = '7aa56eb8f96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_demo_controle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('data_download', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_robo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'versao_id', name='unique_user_versao_demo')
    )
    with op.batch_alter_table('produto_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto_robo', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    op.drop_table('download_demo_controle')
    # ### end Alembic commands ###
