"""adiciona setup_txid e setup_payload para controle de pagamento do setup

Revision ID: b208cc4e793d
Revises: b6ff589a921c
Create Date: 2026-06-11 13:52:52.850549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b208cc4e793d'
down_revision = 'b6ff589a921c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_txid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('setup_payload', sa.Text(), nullable=True))
        batch_op.alter_column('setup_pago',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('setup_pago',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('setup_payload')
        batch_op.drop_column('setup_txid')

    # ### end Alembic commands ###
