"""adiciona campo setup_pago em user para taxa unica de setup

Revision ID: b6ff589a921c
Revises: 5a270dca24b2
Create Date: 2026-06-11 13:32:14.983293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ff589a921c'
down_revision = '5a270dca24b2'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Adiciona a coluna permitindo NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_pago', sa.Boolean(), nullable=True))

    # 2. Preenche os registros existentes com FALSE
    op.execute("UPDATE \"user\" SET setup_pago = FALSE WHERE setup_pago IS NULL")

    # 3. Agora torna a coluna NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('setup_pago', existing_type=sa.Boolean(), nullable=False)

    # 4. Opcional: isenta clientes antigos da cobrança
    op.execute("UPDATE \"user\" SET setup_pago = TRUE WHERE role = 'cliente' AND modelo_negocio = 'comissao'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('setup_pago')

    # ### end Alembic commands ###
