"""fase_1_onboarding

Revision ID: bb3f4f04c309
Revises: 22debf812494
Create Date: 2026-05-20 21:23:04.191069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3f4f04c309'
down_revision = '22debf812494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cliente', schema=None) as batch_op:
        batch_op.alter_column('autentique_document_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('documento_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_template', schema=None) as batch_op:
        batch_op.drop_column('is_onboarding')

    with op.batch_alter_table('documento_cliente', schema=None) as batch_op:
        batch_op.alter_column('autentique_document_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
