"""Alterando para arquivo local nos templates de contrato

Revision ID: c9b06bd2cb37
Revises: 09c2aa102c17
Create Date: 2026-05-11 12:46:01.062590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b06bd2cb37'
down_revision = '09c2aa102c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo_local', sa.String(length=100), nullable=False))
        batch_op.drop_column('autentique_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autentique_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('arquivo_local')

    # ### end Alembic commands ###
