"""adiciona coluna comprovante pix

Revision ID: cae51ed938c0
Revises: 21cfe93f90c6
Create Date: 2026-05-05 11:19:12.903824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae51ed938c0'
down_revision = '21cfe93f90c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprovante_pix', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_column('comprovante_pix')

    # ### end Alembic commands ###
