"""adiciona tabelas robo e licenca

Revision ID: dd259668b058
Revises: bb3f4f04c309
Create Date: 2026-05-26 22:29:10.945491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd259668b058'
down_revision = 'bb3f4f04c309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('arquivo_local', sa.String(length=100), nullable=False),
    sa.Column('is_onboarding', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('status_acesso', sa.String(length=20), nullable=True),
    sa.Column('is_isento', sa.Boolean(), nullable=True),
    sa.Column('modelo_negocio', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('corretora', sa.String(length=50), nullable=True),
    sa.Column('capital_alocado', sa.Float(), nullable=True),
    sa.Column('perfil_risco', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('precisa_trocar_senha', sa.Boolean(), nullable=True),
    sa.Column('termo_assinado', sa.Boolean(), nullable=True),
    sa.Column('docusign_envelope_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('username')
    )
    op.create_table('versao_robo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.String(length=255), nullable=False),
    sa.Column('novidades', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('publicada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alocacao_corretora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_corretora', sa.String(length=50), nullable=False),
    sa.Column('capital_alocado', sa.Float(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('autentique_document_id', sa.String(length=100), nullable=True),
    sa.Column('link_assinatura', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['documento_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_controle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('data_download', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_robo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'versao_id', name='_user_versao_uc')
    )
    op.create_table('fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('bruto', sa.Float(), nullable=True),
    sa.Column('taxas_b3', sa.Float(), nullable=True),
    sa.Column('irrf_1', sa.Float(), nullable=True),
    sa.Column('liquido_pregao', sa.Float(), nullable=True),
    sa.Column('irrf_19', sa.Float(), nullable=True),
    sa.Column('liquido', sa.Float(), nullable=True),
    sa.Column('repasse', sa.Float(), nullable=True),
    sa.Column('comprovante_pix', sa.String(length=255), nullable=True),
    sa.Column('txid_pix', sa.String(length=100), nullable=True),
    sa.Column('payload_pix', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenca_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chave_licenca', sa.String(length=100), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.Column('ciclo_inicio', sa.Date(), nullable=False),
    sa.Column('ciclo_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ciclo_inicio', name='_user_ciclo_uc')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_nome', sa.String(length=100), nullable=False),
    sa.Column('acao_detalhada', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcela_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('txid_pix', sa.String(length=100), nullable=True),
    sa.Column('payload_pix', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatura_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('nome_corretora', sa.String(length=50), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=False),
    sa.Column('is_isento', sa.Boolean(), nullable=True),
    sa.Column('bruto', sa.Float(), nullable=True),
    sa.Column('taxas_b3', sa.Float(), nullable=True),
    sa.Column('irrf_1', sa.Float(), nullable=True),
    sa.Column('liquido_pregao', sa.Float(), nullable=True),
    sa.Column('irrf_19', sa.Float(), nullable=True),
    sa.Column('liquido', sa.Float(), nullable=True),
    sa.Column('repasse', sa.Float(), nullable=True),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['fatura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_id', 'data_pregao', 'nome_corretora', name='_fatura_dia_corretora_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fatura_diaria')
    op.drop_table('parcela_compra')
    op.drop_table('log_auditoria')
    op.drop_table('licenca_cliente')
    op.drop_table('fatura')
    op.drop_table('download_controle')
    op.drop_table('documento_cliente')
    op.drop_table('alocacao_corretora')
    op.drop_table('versao_robo')
    op.drop_table('user')
    op.drop_table('documento_template')
    # ### end Alembic commands ###
