"""adiciona tabelas robo e licenca

Revision ID: e0188ec6d94e
Revises: bb3f4f04c309
Create Date: 2026-05-26 23:24:37.496489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0188ec6d94e'
down_revision = 'bb3f4f04c309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versao_robo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.String(length=255), nullable=False),
    sa.Column('novidades', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('publicada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_controle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('data_download', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_robo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'versao_id', name='_user_versao_uc')
    )
    op.create_table('licenca_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chave_licenca', sa.String(length=100), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.Column('ciclo_inicio', sa.Date(), nullable=False),
    sa.Column('ciclo_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ciclo_inicio', name='_user_ciclo_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenca_cliente')
    op.drop_table('download_controle')
    op.drop_table('versao_robo')
    # ### end Alembic commands ###
