"""adiciona is_isento em fatura_diaria

Revision ID: ec2dad855324
Revises: 115bb3f731b1
Create Date: 2026-05-08 14:08:12.530953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2dad855324'
down_revision = '115bb3f731b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_isento', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_diaria', schema=None) as batch_op:
        batch_op.drop_column('is_isento')

    # ### end Alembic commands ###
