"""adiciona codigo_algoritmo em produto_robo

Revision ID: efdbf520c638
Revises: b208cc4e793d
Create Date: 2026-06-12 10:47:10.008291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdbf520c638'
down_revision = 'b208cc4e793d'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Adiciona a coluna permitindo NULL
    with op.batch_alter_table('produto_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_algoritmo', sa.Integer(), nullable=True))

    # 2. Preenche os registros existentes com os códigos corretos
    op.execute("UPDATE produto_robo SET codigo_algoritmo = 700 WHERE id = 1")
    op.execute("UPDATE produto_robo SET codigo_algoritmo = 1005 WHERE id = 2")
    op.execute("UPDATE produto_robo SET codigo_algoritmo = 1006 WHERE id = 3")

    # 3. Agora torna a coluna NOT NULL
    with op.batch_alter_table('produto_robo', schema=None) as batch_op:
        batch_op.alter_column('codigo_algoritmo', existing_type=sa.Integer(), nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto_robo', schema=None) as batch_op:
        batch_op.drop_column('codigo_algoritmo')

    # ### end Alembic commands ###
